import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compileFromFile } from "json-schema-to-typescript";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(scriptDirectory, "..");
const schemaDirectory = resolve(packageRoot, "schema");
const outputDirectory = resolve(packageRoot, "src", "generated");
const check = process.argv.includes("--check");

const contracts = [
  ["adaptation_beat.v1", "AdaptationBeat"],
  ["agent_goal.v1", "AgentGoal"],
  ["artifact.v1", "Artifact"],
  ["artifact_ref.v1", "ArtifactRef"],
  ["asset_ref.v1", "AssetRef"],
  ["asset_request.v1", "AssetRequest"],
  ["context_pack.v1", "ContextPack"],
  ["generation_run.v1", "GenerationRun"],
  ["manga_manifest.v1", "MangaManifest"],
  ["manga_plan.v1", "MangaPlan"],
  ["memory_delta.v1", "MemoryDelta"],
  ["model_receipt.v1", "ModelReceipt"],
  ["reel_player_payload.v1", "ReelPlayerPayload"],
  ["reel_series.v1", "ReelSeries"],
  ["reel_spec.v1", "ReelSpec"],
  ["rendered_page.v1", "RenderedPage"],
  ["scope_manifest.v1", "ScopeManifest"],
  ["series_progress.v1", "SeriesProgress"],
  ["series_progress_update.v1", "SeriesProgressUpdate"],
  ["source_ref.v1", "SourceRef"],
  ["source_unit.v1", "SourceUnit"],
  ["stage_run.v1", "StageRun"],
];

const bannerComment = [
  "/* eslint-disable */",
  "/**",
  " * Generated from canonical Pydantic JSON Schema.",
  " * Run `npm run generate`; do not edit this file by hand.",
  " */",
].join("\n");

async function updateFile(path, content) {
  let current = null;
  try {
    current = await readFile(path, "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  if (current === content) return false;
  if (!check) await writeFile(path, content, "utf8");
  return true;
}

await mkdir(outputDirectory, { recursive: true });
const changed = [];

for (const [contractName] of contracts) {
  const schemaPath = resolve(schemaDirectory, `${contractName}.schema.json`);
  const outputPath = resolve(outputDirectory, `${contractName}.ts`);
  const output = await compileFromFile(schemaPath, {
    bannerComment,
    cwd: schemaDirectory,
    style: { singleQuote: false },
    unreachableDefinitions: false,
  });
  if (await updateFile(outputPath, output)) changed.push(outputPath);
}

const index = [
  bannerComment,
  "",
  ...contracts.map(
    ([contractName, typeName]) =>
      `export type { ${typeName} } from "./${contractName}.js";`,
  ),
  "",
].join("\n");
const indexPath = resolve(outputDirectory, "index.ts");
if (await updateFile(indexPath, index)) changed.push(indexPath);

if (check && changed.length > 0) {
  console.error("Generated TypeScript contracts are out of date:");
  for (const path of changed) console.error(path);
  process.exitCode = 1;
} else {
  console.log(`Generated TypeScript contracts are current (${contracts.length} contracts).`);
}
